apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-db-init
  namespace: payments
data:
  init-db.sh: |-
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      SELECT 'CREATE DATABASE payments' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'payments');
    EOSQL