apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
      - name: payments-api
        image: 131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/payments:latest
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: payments-secret
              key: database-url
        # Corrigido o host do RabbitMQ para usar o formato de DNS completo
        - name: RABBITMQ_HOST
          value: rabbitmq.payments.svc.cluster.local
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: payments-secret
              key: rabbitmq-user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: payments-secret
              key: rabbitmq-password
        # Adicionada a URL do serviço de pedidos
        - name: SERVICE_ORDERS_URL
          value: "http://orders-service.orders.svc.cluster.local:8003"
        command: ["uvicorn", "tech.api.app:app", "--host", "0.0.0.0", "--port", "8004"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"