#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: payments-postgres-pvc
#  namespace: payments
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi