apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: payments
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # postgres em base64
  postgres-password: cG9zdGdyZXM=  # postgres em base64
  postgres-db: cGF5bWVudHM=  # payments em base64
  database-url: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cG9zdGdyZXNAcGF5bWVudHMtcG9zdGdyZXM6NTQzMi9wYXltZW50cw==  # postgresql+psycopg://postgres:postgres@payments-postgres:5432/payments em base64
  rabbitmq-user: dXNlcg==  # user em base64
  rabbitmq-password: cGFzc3dvcmQ=  # password em base64