apiVersion: v1
kind: Service
metadata:
  name: payments-api-external
  namespace: payments
spec:
  ports:
  - port: 8004
    targetPort: 8004
    name: http
  selector:
    app: payments-api
  type: LoadBalancer